# Generated by Django 2.2 on 2019-04-03 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('DOB', models.DateField(default=datetime.date.today)),
                ('SSN', models.CharField(max_length=9)),
                ('monthly_views', models.IntegerField(default=-1)),
                ('Genre', models.CharField(max_length=15)),
                ('label_rank', models.IntegerField(default=-1)),
            ],
        ),
    ]
