# Generated by Django 2.2 on 2019-04-09 01:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('label', models.CharField(max_length=25)),
                ('sales', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('DOB', models.DateField(default=datetime.date.today)),
                ('SSN', models.CharField(max_length=9)),
                ('monthly_views', models.IntegerField(default=-1)),
                ('Genre', models.CharField(max_length=15)),
                ('label_rank', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.IntegerField(primary_key=True, serialize=False)),
                ('track', models.CharField(max_length=25)),
                ('length', models.DateTimeField(default=datetime.date.today)),
                ('streams', models.IntegerField(default=-1)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Artist')),
                ('featured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_artist', to='search.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Artist'),
        ),
    ]
