# Generated by Django 2.2 on 2019-04-09 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
