# Generated by Django 2.2 on 2019-04-09 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_album_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='featured',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_artist', to='search.Artist'),
        ),
    ]
