# Generated by Django 2.2 on 2019-04-09 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20190409_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
