# Generated by Django 2.2 on 2019-04-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20190409_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='DOB',
            field=models.DateField(blank=True),
        ),
    ]
